version: "3.8"
services:
  app:
    container_name: jams
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    ports:
      - ${APP_HOST_PORT}:${APP_CONTAINER_PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    container_name: database
    image: ${DB_IMAGE}
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  db_data:
    driver: local